import type { Metadata } from "next";
import { Arizonia, Georama } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const arizonia = Arizonia({
  variable: "--font-arizonia",
  subsets: ["latin"],
  weight: "400",
});

const georama = Georama({
  variable: "--font-georama",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${georama.className} text-primary antialiased`}>
        <Navbar arizoniaClass={arizonia.className} />
        {children}
      </body>
    </html>
  );
}
